@extends('layouts.master')
@section('main-content')
@section('page-css')
    <link rel="stylesheet" href="{{ asset('assets/styles/vendor/datatables.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/styles/vendor/nprogress.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/styles/vendor/flatpickr.min.css') }}">
    <meta name="csrf-token" content="{{ csrf_token() }}">
@endsection

<div class="breadcrumb">

    <h1>{{ __('Pos Products') }}</h1>
</div>
<div class="separator-breadcrumb border-top"></div>
<div class="row" id="section_product_list">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                @if ($message = Session::get('success'))
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        <strong>Success!</strong> {{ $message }}.
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                @endif
                <div class="d-flex align-items-center justify-content-between text-end mb-3 mt-2">
                    <div class="form-group d-flex align-items-start justify-content-center flex-column">
                        <label for="warehouse_id">{{ __('translate.Warehouse') }}</label>
                        <select class="form-select" style="width: 150px!important" name="warehouse_id"
                            id="warehouse_id">
                            <option selected disabled>Select Warehouse</option>
                            @foreach ($warehouses as $warehouse)
                                <option value="{{ $warehouse->id }}"
                                    {{ $warehouse->id == $settings->warehouse_id ? 'selected' : '' }}>
                                    {{ $warehouse->name }}
                                </option>
                            @endforeach
                        </select>
                    </div>
                    <div class="div">
                        @can('products_add')
                            <a href="{{ route('pos-product.create') }}" class=" btn btn-outline-primary btn-md m-1"><i
                                    class="i-Add me-2 font-weight-bold"></i>
                                {{ __('translate.Create') }}</a>
                            <button id="printButton" class="btn btn-outline-success ms-3 fw-bolder"><i
                                    class="i-Add me-2 font-weight-bold"></i>Print</button>
                        @endcan
                    </div>
                </div>

                <div class="table-responsive">
                    <table id="dataTable" class="display">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Image</th>
                                <th>Name</th>
                                <th>Category</th>
                                <th>Price</th>
                                <th>Online Price</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody id="table_body">
                            <!-- Table body content will be dynamically generated by your JavaScript -->
                        </tbody>
                    </table>
                </div>

            </div>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div style="background-color: white; border:0px;" class="modal-content">
            <div style="display: flex; flex-direction: column; align-items: center; padding-top: 20px;"
                class="modal-body">
                <div class="swal2-icon swal2-warning pulse-warning" style="display: block;">!</div>
                <h2
                    style="color: #595959; font-size: 30px; font-weight: 600; text-transform: none; margin: 0; padding: 0; line-height: 60px; display: block;">
                    Are you sure?
                </h2>
                <div class="swal2-content"
                    style="font-size: 18px; text-align: center; font-weight: 300; position: relative; float: none; margin: 0; padding: 0; line-height: normal; color: #545454;">
                    You won't be able to revert this!
                </div>
            </div>
            <div style="justify-content: center; border-top: 0px; padding: 40px 0px 20px 0px;" class="modal-footer">
                <button data-dismiss="modal" aria-label="Close" type="button" id="deleteBtn"
                    class="swal2-confirm btn btn-primary me-5 btn-ok">
                    Yes, delete it
                </button>
                <button data-dismiss="modal" aria-label="Close" id="cancelBtn" type="button"
                    class="swal2-cancel btn btn-danger" style="display: inline-block;">
                    No, cancel!
                </button>
            </div>
            <input type="hidden" id="deleteDepartmentId" value="">
        </div>
    </div>
</div>
<!-- Modal End-->

@endsection
@section('page-js')
<script src="{{ asset('assets/js/vendor/datatables.min.js') }}"></script>
<script src="{{ asset('assets/js/nprogress.js') }}"></script>
<script src="{{ asset('assets/js/flatpickr.min.js') }}"></script>
<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<!-- Add these lines to include DataTables -->
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.5/css/jquery.dataTables.css">
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.js"></script>
<!-- Include jQuery -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<!-- Include DataTables CSS and JS -->
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.25/css/jquery.dataTables.min.css">
<script type="text/javascript" src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js"></script>


<script src="{{ asset('assets/js/vendor/datatables.min.js') }}"></script>
<script type="text/javascript">
    function Remove_Product(id) {
        $("#deleteDepartmentId").val(id);
        $("#deleteModal").modal("show");
    }

    $("#cancelBtn").click(function() {
        $("#deleteModal").modal("hide");
        $("#deleteDepartmentId").val("");
    })

    $(document).ready(function() {

        getData($("#warehouse_id").val());

        function getData(id) {
            $.ajax({
                type: "GET",
                url: "{{ route('pos-product.getPosProducts') }}",
                dataType: "json",
                headers: {
                    "X-CSRF-TOKEN": "{{ csrf_token() }}"
                },
                data: {
                    id: id
                },
                success: function(response) {
                    $("#table_body").empty();
                    $('#dataTable').DataTable().destroy();
                    // Add DataTable initialization
                    var dataTable = $('#dataTable').DataTable({
                        data: response,
                        columns: [{
                                data: 'id'
                            },
                            {
                                data: 'img_path',
                                render: function(data) {
                                    if (data) {
                                        return '<img src="/images/products/' +
                                            data + '" width="50px" height="50px">';
                                    } else {
                                        // If img_path is null, provide a default image
                                        return '<img src="/images/products/no_image.png" width="50px" height="50px">';
                                    }
                                }
                            },
                            {
                                data: 'name'
                            },
                            {
                                data: 'category.name'
                            },
                            {
                                data: 'price'
                            },
                            {
                                data: 'online_product_price'
                            },
                            {
                                data: null,
                                render: function(data, type, row) {
                                    var actions = '';
                                    @can('products_edit')
                                        actions +=
                                            '<a href="{{ url('/pos-product/edit/') }}/' +
                                            row
                                            .id +
                                            '" class="cursor-pointer ul-link-action text-success" data-toggle="tooltip" data-placement="top" title="Edit"><i class="i-Edit"></i></a>';
                                    @endcan
                                    @can('products_delete')
                                        actions += '<a onclick="Remove_Product(' +
                                            row.id +
                                            ')" class="cursor-pointer ul-link-action text-danger mr-1" data-toggle="tooltip" data-placement="top" title="Delete"><i class="i-Close-Window"></i></a>';
                                    @endcan
                                    return actions;
                                }
                            },
                        ],
                        // Add any other DataTable options you need
                        paging: true,
                        searching: true
                    });
                }
            });
        }

        $("#warehouse_id").on('change', function() {
            var id = $("#warehouse_id").val();
            getData(id);
        });

        $("#deleteBtn").click(function() {
            var id = $("#deleteDepartmentId").val();
            $.ajax({
                type: "DELETE",
                url: "{{ route('pos-product.delete') }}",
                data: {
                    id: id,
                },
                dataType: "json",
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                },
                success: function(response) {
                    $("#deleteModal").modal("hide");
                    $("#deleteDepartmentId").val("");
                    $("#cancelBtn").click();
                    getData();
                    toastr.success(response.message);
                },
                error: function(xhr) {
                    console.log(xhr.responseText);
                    // Handle errors and display them on the same page
                    toastr.error('Something went wrong. Please try again later.');

                }
            })
        })

    });
</script>

{{-- print --}}
<script>
    document.getElementById("printButton").addEventListener("click", function() {
        var table = document.getElementById("dataTable");
        if (table) {
            // Clone the table
            var tableClone = table.cloneNode(true);

            // Exclude the "image" column
            Array.from(tableClone.rows).forEach(function(row) {
                row.deleteCell(5); // Remove the first column
                row.deleteCell(1); // Remove the second column
            });

            var newWin = window.open('', 'Print-Window');
            newWin.document.open();
            newWin.document.write(
                '<html><head><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"></head><body>' +
                tableClone.outerHTML + '</body></html>');
            newWin.document.close();
            setTimeout(function() {
                newWin.print();
                newWin.close();
            }, 10);
        }
    });
</script>
@endsection
